

#include <cstdint>
#include <cstring>

namespace {

struct CheckPlace {
    const char* check;
    const char* place;
};

const CheckPlace kPlaces[] = {
    {"Forest Temple Gale Boomerang", "Forest Temple Gale Boomerang"},
    {"archery_reward:F_SP109", "Talo Sharpshooting"},
    {"ashei_sketch", "Ashei Sketch"},
    {"auru_memo", "Auru Gift To Fyer"},
    {"ball_and_chain:D_MN11", "Snowpeak Ruins Ball and Chain"},
    {"boss:D_MN01A", "Lakebed Temple Morpheel Heart Container"},
    {"boss:D_MN04A", "Goron Mines Fyrus Heart Container"},
    {"boss:D_MN05A", "Forest Temple Diababa Heart Container"},
    {"boss:D_MN06A", "Temple of Time Armogohma Heart Container"},
    {"boss:D_MN07A", "City in the Sky Argorok Heart Container"},
    {"boss:D_MN10A", "Arbiter's Grounds Stallord Heart Container"},
    {"boss:D_MN11A", "Snowpeak Ruins Blizzeta Heart Container"},
    {"bug:192", "Agitha Male Beetle Reward"},
    {"bug:193", "Agitha Female Beetle Reward"},
    {"bug:194", "Agitha Male Butterfly Reward"},
    {"bug:195", "Agitha Female Butterfly Reward"},
    {"bug:196", "Agitha Male Stag Beetle Reward"},
    {"bug:197", "Agitha Female Stag Beetle Reward"},
    {"bug:198", "Agitha Male Grasshopper Reward"},
    {"bug:199", "Agitha Female Grasshopper Reward"},
    {"bug:200", "Agitha Male Phasmid Reward"},
    {"bug:201", "Agitha Female Phasmid Reward"},
    {"bug:202", "Agitha Male Pill Bug Reward"},
    {"bug:203", "Agitha Female Pill Bug Reward"},
    {"bug:204", "Agitha Male Mantis Reward"},
    {"bug:205", "Agitha Female Mantis Reward"},
    {"bug:206", "Agitha Male Ladybug Reward"},
    {"bug:207", "Agitha Female Ladybug Reward"},
    {"bug:208", "Agitha Male Snail Reward"},
    {"bug:209", "Agitha Female Snail Reward"},
    {"bug:210", "Agitha Male Dragonfly Reward"},
    {"bug:211", "Agitha Female Dragonfly Reward"},
    {"bug:212", "Agitha Male Ant Reward"},
    {"bug:213", "Agitha Female Ant Reward"},
    {"bug:214", "Agitha Male Dayfly Reward"},
    {"bug:215", "Agitha Female Dayfly Reward"},
    {"bulblin_key:D_MN09", "Hyrule Castle King Bulblin Key"},
    {"chest:D_MN01:1", "Lakebed Temple Central Room Small Chest"},
    {"chest:D_MN01:10", "Lakebed Temple East Second Floor Southeast Chest"},
    {"chest:D_MN01:11", "Lakebed Temple East Water Supply Clawshot Chest"},
    {"chest:D_MN01:12", "Lakebed Temple Big Key Chest"},
    {"chest:D_MN01:13", "Lakebed Temple West Second Floor Northeast Chest"},
    {"chest:D_MN01:14", "Lakebed Temple Before Deku Toad Underwater Right Chest"},
    {"chest:D_MN01:15", "Lakebed Temple Before Deku Toad Underwater Left Chest"},
    {"chest:D_MN01:16", "Lakebed Temple Central Room Spire Chest"},
    {"chest:D_MN01:17", "Lakebed Temple Central Room Chest"},
    {"chest:D_MN01:18", "Lakebed Temple Underwater Maze Small Chest"},
    {"chest:D_MN01:19", "Lakebed Temple West Second Floor Central Small Chest"},
    {"chest:D_MN01:2", "Lakebed Temple Before Deku Toad Alcove Chest"},
    {"chest:D_MN01:20", "Lakebed Temple West Water Supply Chest"},
    {"chest:D_MN01:21", "Lakebed Temple West Water Supply Small Chest"},
    {"chest:D_MN01:24", "Lakebed Temple East Second Floor Southwest Chest"},
    {"chest:D_MN01:25", "Lakebed Temple West Second Floor Southwest Underwater Chest"},
    {"chest:D_MN01:27", "Lakebed Temple East Water Supply Small Chest"},
    {"chest:D_MN01:28", "Lakebed Temple Lobby Left Chest"},
    {"chest:D_MN01:29", "Lakebed Temple Lobby Rear Chest"},
    {"chest:D_MN01:3", "Lakebed Temple Stalactite Room Chest"},
    {"chest:D_MN01:30", "Lakebed Temple West Lower Small Chest"},
    {"chest:D_MN01:5", "Lakebed Temple Chandelier Chest"},
    {"chest:D_MN01:6", "Lakebed Temple East Lower Waterwheel Stalactite Chest"},
    {"chest:D_MN01:7", "Lakebed Temple West Second Floor Southeast Chest"},
    {"chest:D_MN01:8", "Lakebed Temple East Lower Waterwheel Bridge Chest"},
    {"chest:D_MN01B:0", "Lakebed Temple Deku Toad Chest"},
    {"chest:D_MN04:11", "Goron Mines Main Magnet Room Bottom Chest"},
    {"chest:D_MN04:12", "Goron Mines Beamos Room Chest"},
    {"chest:D_MN04:13", "Goron Mines Chest Before Dangoro"},
    {"chest:D_MN04:14", "Goron Mines Outside Clawshot Chest"},
    {"chest:D_MN04:15", "Goron Mines Outside Beamos Chest"},
    {"chest:D_MN04:16", "Goron Mines Crystal Switch Room Underwater Chest"},
    {"chest:D_MN04:17", "Goron Mines Gor Amato Chest"},
    {"chest:D_MN04:20", "Goron Mines Magnet Maze Chest"},
    {"chest:D_MN04:21", "Goron Mines Outside Underwater Chest"},
    {"chest:D_MN04:24", "Goron Mines Gor Amato Small Chest"},
    {"chest:D_MN04:25", "Goron Mines Gor Ebizo Chest"},
    {"chest:D_MN04:26", "Goron Mines Gor Liggs Chest"},
    {"chest:D_MN04:27", "Goron Mines Entrance Chest"},
    {"chest:D_MN04:28", "Goron Mines Crystal Switch Room Small Chest"},
    {"chest:D_MN04:30", "Goron Mines Main Magnet Room Top Chest"},
    {"chest:D_MN04:6", "Goron Mines Dangoro Chest"},
    {"chest:D_MN04:9", "Goron Mines After Crystal Switch Room Magnet Wall Chest"},
    {"chest:D_MN05:1", "Forest Temple East Tile Worm Chest"},
    {"chest:D_MN05:19", "Forest Temple West Tile Worm Chest Behind Stairs"},
    {"chest:D_MN05:2", "Forest Temple North Deku Like Chest"},
    {"chest:D_MN05:20", "Forest Temple Central Chest Hanging From Web"},
    {"chest:D_MN05:24", "Forest Temple West Tile Worm Room Vines Chest"},
    {"chest:D_MN05:25", "Forest Temple Totem Pole Chest"},
    {"chest:D_MN05:26", "Forest Temple East Water Cave Chest"},
    {"chest:D_MN05:31", "Forest Temple West Deku Like Chest"},
    {"chest:D_MN05:37", "Forest Temple Central Chest Behind Stairs"},
    {"chest:D_MN05:38", "Forest Temple Big Key Chest"},
    {"chest:D_MN05:39", "Forest Temple Central North Chest"},
    {"chest:D_MN05:4", "Forest Temple Windless Bridge Chest"},
    {"chest:D_MN05:7", "Forest Temple Entrance Vines Chest"},
    {"chest:D_MN05:9", "Forest Temple Second Monkey Under Bridge Chest"},
    {"chest:D_MN06:1", "Temple of Time First Staircase Armos Chest"},
    {"chest:D_MN06:12", "Temple of Time Moving Wall Dinalfos Room Chest"},
    {"chest:D_MN06:2", "Temple of Time First Staircase Gohma Gate Chest"},
    {"chest:D_MN06:4", "Temple of Time Armos Antechamber East Chest"},
    {"chest:D_MN06:41", "Temple of Time Lobby Lantern Chest"},
    {"chest:D_MN06:43", "Temple of Time Chest Before Darknut"},
    {"chest:D_MN06:44", "Temple of Time Scales Gohma Chest"},
    {"chest:D_MN06:45", "Temple of Time First Staircase Window Chest"},
    {"chest:D_MN06:46", "Temple of Time Armos Antechamber North Chest"},
    {"chest:D_MN06:47", "Temple of Time Scales Upper Chest"},
    {"chest:D_MN06:48", "Temple of Time Floor Switch Puzzle Room Upper Chest"},
    {"chest:D_MN06:5", "Temple of Time Armos Antechamber Statue Chest"},
    {"chest:D_MN06:6", "Temple of Time Moving Wall Beamos Room Chest"},
    {"chest:D_MN06:8", "Temple of Time Big Key Chest"},
    {"chest:D_MN06:9", "Temple of Time Gilloutine Chest"},
    {"chest:D_MN06B:0", "Temple of Time Darknut Chest"},
    {"chest:D_MN07:11", "City in the Sky West Garden Lower Chest"},
    {"chest:D_MN07:12", "City in the Sky Central Outside Poe Island Chest"},
    {"chest:D_MN07:13", "City in the Sky Big Key Chest"},
    {"chest:D_MN07:14", "City in the Sky Chest Below Big Key Chest"},
    {"chest:D_MN07:15", "City in the Sky West Garden Corner Chest"},
    {"chest:D_MN07:17", "City in the Sky Chest Behind North Fan"},
    {"chest:D_MN07:18", "City in the Sky East Wing After Dinalfos Alcove Chest"},
    {"chest:D_MN07:19", "City in the Sky East Tile Worm Small Chest"},
    {"chest:D_MN07:2", "City in the Sky East First Wing Chest After Fans"},
    {"chest:D_MN07:20", "City in the Sky West Wing Tile Worm Chest"},
    {"chest:D_MN07:21", "City in the Sky West Wing Baba Balcony Chest"},
    {"chest:D_MN07:22", "City in the Sky West Wing Narrow Ledge Chest"},
    {"chest:D_MN07:23", "City in the Sky Baba Tower Narrow Ledge Chest"},
    {"chest:D_MN07:24", "City in the Sky Central Outside Ledge Chest"},
    {"chest:D_MN07:25", "City in the Sky West Garden Lone Island Chest"},
    {"chest:D_MN07:26", "City in the Sky East Wing After Dinalfos Ledge Chest"},
    {"chest:D_MN07:27", "City in the Sky Underwater East Chest"},
    {"chest:D_MN07:3", "City in the Sky Underwater West Chest"},
    {"chest:D_MN07:4", "City in the Sky East Wing Lower Level Chest"},
    {"chest:D_MN07:5", "City in the Sky West Wing First Chest"},
    {"chest:D_MN07:6", "City in the Sky Baba Tower Alcove Chest"},
    {"chest:D_MN07:7", "City in the Sky Baba Tower Top Small Chest"},
    {"chest:D_MN07:9", "City in the Sky West Garden Ledge Chest"},
    {"chest:D_MN07B:0", "City in the Sky Aeralfos Chest"},
    {"chest:D_MN08:0", "Palace of Twilight East Wing First Room East Alcove Chest"},
    {"chest:D_MN08:22", "Palace of Twilight Central First Room Chest"},
    {"chest:D_MN08:23", "Palace of Twilight Big Key Chest"},
    {"chest:D_MN08:24", "Palace of Twilight Central Outdoor Chest"},
    {"chest:D_MN08:25", "Palace of Twilight West Wing Second Room Southeast Chest"},
    {"chest:D_MN08:26", "Palace of Twilight Central Tower Chest"},
    {"chest:D_MN08:27", "Palace of Twilight East Wing First Room West Alcove Chest"},
    {"chest:D_MN08:28", "Palace of Twilight East Wing Second Room Northeast Chest"},
    {"chest:D_MN08:29", "Palace of Twilight East Wing Second Room Northwest Chest"},
    {"chest:D_MN08:3", "Palace of Twilight West Wing Second Room Lower South Chest"},
    {"chest:D_MN08:30", "Palace of Twilight West Wing Chest Behind Wall of Darkness"},
    {"chest:D_MN08:33", "Palace of Twilight East Wing Second Room Southwest Chest"},
    {"chest:D_MN08:36", "Palace of Twilight East Wing First Room North Small Chest"},
    {"chest:D_MN08:4", "Palace of Twilight West Wing First Room Central Chest"},
    {"chest:D_MN08:5", "Palace of Twilight West Wing Second Room Central Chest"},
    {"chest:D_MN08:6", "Palace of Twilight East Wing First Room Zant Head Chest"},
    {"chest:D_MN08:7", "Palace of Twilight East Wing Second Room Southeast Chest"},
    {"chest:D_MN09:0", "Hyrule Castle Big Key Chest"},
    {"chest:D_MN09:1", "Hyrule Castle Southeast Balcony Tower Chest"},
    {"chest:D_MN09:11", "Hyrule Castle East Wing Balcony Chest"},
    {"chest:D_MN09:13", "Hyrule Castle Main Hall Northwest Chest"},
    {"chest:D_MN09:15", "Hyrule Castle Treasure Room First Chest"},
    {"chest:D_MN09:16", "Hyrule Castle Treasure Room Second Chest"},
    {"chest:D_MN09:17", "Hyrule Castle Treasure Room Third Chest"},
    {"chest:D_MN09:18", "Hyrule Castle Treasure Room Fourth Chest"},
    {"chest:D_MN09:19", "Hyrule Castle Treasure Room Fifth Chest"},
    {"chest:D_MN09:2", "Hyrule Castle Main Hall Southwest Chest"},
    {"chest:D_MN09:21", "Hyrule Castle Treasure Room Third Small Chest"},
    {"chest:D_MN09:22", "Hyrule Castle Treasure Room Fifth Small Chest"},
    {"chest:D_MN09:23", "Hyrule Castle Treasure Room Fourth Small Chest"},
    {"chest:D_MN09:25", "Hyrule Castle Lantern Staircase Chest"},
    {"chest:D_MN09:26", "Hyrule Castle Treasure Room Sixth Small Chest"},
    {"chest:D_MN09:27", "Hyrule Castle Treasure Room Seventh Small Chest"},
    {"chest:D_MN09:28", "Hyrule Castle Treasure Room Eighth Small Chest"},
    {"chest:D_MN09:29", "Hyrule Castle Treasure Room Second Small Chest"},
    {"chest:D_MN09:3", "Hyrule Castle King Bulblin Key"},
    {"chest:D_MN09:30", "Hyrule Castle Graveyard Grave Switch Room Right Chest"},
    {"chest:D_MN09:33", "Hyrule Castle Graveyard Grave Switch Room Front Left Chest"},
    {"chest:D_MN09:34", "Hyrule Castle Graveyard Grave Switch Room Back Left Chest"},
    {"chest:D_MN09:35", "Hyrule Castle Treasure Room First Small Chest"},
    {"chest:D_MN09:4", "Hyrule Castle East Wing Boomerang Puzzle Chest"},
    {"chest:D_MN09:5", "Hyrule Castle West Courtyard Central Small Chest"},
    {"chest:D_MN09:7", "Hyrule Castle Graveyard Owl Statue Chest"},
    {"chest:D_MN09:8", "Hyrule Castle Main Hall Northeast Chest"},
    {"chest:D_MN09:9", "Hyrule Castle West Courtyard North Small Chest"},
    {"chest:D_MN10:16", "Arbiter's Grounds West Stalfos Northeast Chest"},
    {"chest:D_MN10:17", "Arbiter's Grounds West Stalfos West Chest"},
    {"chest:D_MN10:18", "Arbiter's Grounds Torch Room West Chest"},
    {"chest:D_MN10:19", "Arbiter's Grounds Torch Room East Chest"},
    {"chest:D_MN10:20", "Arbiter's Grounds Big Key Chest"},
    {"chest:D_MN10:21", "Arbiter's Grounds Ghoul Rat Room Chest"},
    {"chest:D_MN10:23", "Arbiter's Grounds Entrance Chest"},
    {"chest:D_MN10:24", "Arbiter's Grounds North Turning Room Chest"},
    {"chest:D_MN10:25", "Arbiter's Grounds West Small Chest Behind Block"},
    {"chest:D_MN10:26", "Arbiter's Grounds Spinner Room Stalfos Alcove Chest"},
    {"chest:D_MN10:27", "Arbiter's Grounds Spinner Room Second Small Chest"},
    {"chest:D_MN10:28", "Arbiter's Grounds Spinner Room First Small Chest"},
    {"chest:D_MN10:29", "Arbiter's Grounds Spinner Room Lower Central Small Chest"},
    {"chest:D_MN10:3", "Arbiter's Grounds West Chandelier Chest"},
    {"chest:D_MN10:30", "Arbiter's Grounds Spinner Room Lower North Chest"},
    {"chest:D_MN10:4", "Arbiter's Grounds East Upper Turnable Chest"},
    {"chest:D_MN10:5", "Arbiter's Grounds East Upper Turnable Redead Chest"},
    {"chest:D_MN10:6", "Arbiter's Grounds East Lower Turnable Redead Chest"},
    {"chest:D_MN10B:11", "Arbiter's Grounds Death Sword Chest"},
    {"chest:D_MN11:1", "Snowpeak Ruins Wooden Beam Central Chest"},
    {"chest:D_MN11:10", "Snowpeak Ruins Ordon Pumpkin Chest"},
    {"chest:D_MN11:11", "Snowpeak Ruins Chapel Chest"},
    {"chest:D_MN11:13", "Snowpeak Ruins West Courtyard Buried Chest"},
    {"chest:D_MN11:14", "Snowpeak Ruins East Courtyard Buried Chest"},
    {"chest:D_MN11:15", "Snowpeak Ruins East Courtyard Chest"},
    {"chest:D_MN11:18", "Snowpeak Ruins Northeast Chandelier Chest"},
    {"chest:D_MN11:19", "Snowpeak Ruins West Cannon Room Corner Chest"},
    {"chest:D_MN11:2", "Snowpeak Ruins Wooden Beam Northwest Chest"},
    {"chest:D_MN11:20", "Snowpeak Ruins West Cannon Room Central Chest"},
    {"chest:D_MN11:21", "Snowpeak Ruins Lobby Chandelier Chest"},
    {"chest:D_MN11:22", "Snowpeak Ruins Lobby East Armor Chest"},
    {"chest:D_MN11:23", "Snowpeak Ruins Lobby West Armor Chest"},
    {"chest:D_MN11:25", "Snowpeak Ruins Broken Floor Chest"},
    {"chest:D_MN11:3", "Snowpeak Ruins Courtyard Central Chest"},
    {"chest:D_MN11:7", "Snowpeak Ruins Wooden Beam Chandelier Chest"},
    {"chest:D_MN11B:6", "Snowpeak Ruins Chest After Darkhammer"},
    {"chest:D_SB00:0", "Lanayru Ice Block Puzzle Cave Chest"},
    {"chest:D_SB02:61", "Eldin Lantern Cave First Chest"},
    {"chest:D_SB02:62", "Eldin Lantern Cave Lantern Chest"},
    {"chest:D_SB02:63", "Eldin Lantern Cave Second Chest"},
    {"chest:D_SB03:0", "Lake Lantern Cave Fourth Chest"},
    {"chest:D_SB03:1", "Lake Lantern Cave First Chest"},
    {"chest:D_SB03:10", "Lake Lantern Cave Eighth Chest"},
    {"chest:D_SB03:11", "Lake Lantern Cave Twelfth Chest"},
    {"chest:D_SB03:12", "Lake Lantern Cave Thirteenth Chest"},
    {"chest:D_SB03:13", "Lake Lantern Cave Fourteenth Chest"},
    {"chest:D_SB03:14", "Lake Lantern Cave Seventh Chest"},
    {"chest:D_SB03:2", "Lake Lantern Cave Second Chest"},
    {"chest:D_SB03:3", "Lake Lantern Cave End Lantern Chest"},
    {"chest:D_SB03:4", "Lake Lantern Cave Eleventh Chest"},
    {"chest:D_SB03:5", "Lake Lantern Cave Tenth Chest"},
    {"chest:D_SB03:6", "Lake Lantern Cave Third Chest"},
    {"chest:D_SB03:7", "Lake Lantern Cave Fifth Chest"},
    {"chest:D_SB03:8", "Lake Lantern Cave Sixth Chest"},
    {"chest:D_SB03:9", "Lake Lantern Cave Ninth Chest"},
    {"chest:D_SB04:61", "Eldin Stockcave Lantern Chest"},
    {"chest:D_SB04:62", "Eldin Stockcave Lowest Chest"},
    {"chest:D_SB04:63", "Eldin Stockcave Upper Chest"},
    {"chest:D_SB05:0", "West Hyrule Field Helmasaur Grotto Chest"},
    {"chest:D_SB05:10", "Eldin Field Bomskit Grotto Left Chest"},
    {"chest:D_SB05:6", "Eldin Field Bomskit Grotto Lantern Chest"},
    {"chest:D_SB05:7", "Ordon Ranch Grotto Lantern Chest"},
    {"chest:D_SB06:11", "Faron Field Corner Grotto Left Chest"},
    {"chest:D_SB06:12", "Faron Field Corner Grotto Right Chest"},
    {"chest:D_SB06:13", "Faron Field Corner Grotto Rear Chest"},
    {"chest:D_SB06:17", "Eldin Field Stalfos Grotto Right Small Chest"},
    {"chest:D_SB06:18", "Eldin Field Stalfos Grotto Left Small Chest"},
    {"chest:D_SB06:2", "Eldin Field Stalfos Grotto Stalfos Chest"},
    {"chest:D_SB06:3", "Sacred Grove Baba Serpent Grotto Chest"},
    {"chest:D_SB07:14", "Gerudo Desert Rock Grotto Lantern Chest"},
    {"chest:D_SB08:15", "Snowpeak Freezard Grotto Chest"},
    {"chest:D_SB08:19", "Lanayru Field Skulltula Grotto Chest"},
    {"chest:D_SB08:4", "Lake Hylia Bridge Bubble Grotto Chest"},
    {"chest:D_SB08:8", "Gerudo Desert Skulltula Grotto Chest"},
    {"chest:D_SB09:1", "Outside South Castle Town Tektite Grotto Chest"},
    {"chest:D_SB09:16", "Eldin Field Water Bomb Fish Grotto Chest"},
    {"chest:D_SB09:21", "Lake Hylia Shell Blade Grotto Chest"},
    {"chest:D_SB09:5", "Lake Hylia Water Toadpoli Grotto Chest"},
    {"chest:D_SB10:31", "South Faron Cave Chest"},
    {"chest:F_SP108:24", "Faron Mist Cave Open Chest"},
    {"chest:F_SP108:26", "Faron Mist Cave Lantern Chest"},
    {"chest:F_SP108:27", "Faron Mist North Chest"},
    {"chest:F_SP108:28", "Faron Mist Stump Chest"},
    {"chest:F_SP108:29", "Faron Mist South Chest"},
    {"chest:F_SP108:30", "Faron Woods Owl Statue Chest"},
    {"chest:F_SP108:63", "North Faron Woods Deku Baba Chest"},
    {"chest:F_SP109:20", "Kakariko Watchtower Alcove Chest"},
    {"chest:F_SP109:21", "Eldin Spring Underwater Chest"},
    {"chest:F_SP110:22", "Death Mountain Alcove Chest"},
    {"chest:F_SP111:24", "Kakariko Graveyard Lantern Chest"},
    {"chest:F_SP113:19", "Zora's Domain Light All Torches Chest"},
    {"chest:F_SP113:20", "Zora's Domain Extinguish All Torches Chest"},
    {"chest:F_SP113:26", "Zora's Domain Chest Behind Waterfall"},
    {"chest:F_SP113:30", "Zora's Domain Chest By Mother and Child Isles"},
    {"chest:F_SP114:0", "Snowpeak Cave Ice Lantern Chest"},
    {"chest:F_SP115:0", "Flight By Fowl Second Platform Chest"},
    {"chest:F_SP115:1", "Outside Lanayru Spring Left Statue Chest"},
    {"chest:F_SP115:10", "Lanayru Spring Underwater Right Chest"},
    {"chest:F_SP115:12", "Lanayru Spring Underwater Left Chest"},
    {"chest:F_SP115:2", "Flight By Fowl Third Platform Chest"},
    {"chest:F_SP115:25", "Flight By Fowl Top Platform Reward"},
    {"chest:F_SP115:27", "Lanayru Spring Back Room Right Chest"},
    {"chest:F_SP115:28", "Lanayru Spring Back Room Left Chest"},
    {"chest:F_SP115:29", "Lanayru Spring Back Room Lantern Chest"},
    {"chest:F_SP115:3", "Lanayru Spring West Double Clawshot Chest"},
    {"chest:F_SP115:4", "Lanayru Spring East Double Clawshot Chest"},
    {"chest:F_SP115:5", "Lake Hylia Underwater Chest"},
    {"chest:F_SP115:6", "Outside Lanayru Spring Right Statue Chest"},
    {"chest:F_SP115:7", "Flight By Fowl Fifth Platform Chest"},
    {"chest:F_SP115:8", "Flight By Fowl Fourth Platform Chest"},
    {"chest:F_SP116:1", "Doctor's Office Balcony Chest"},
    {"chest:F_SP117:1", "Sacred Grove Past Owl Statue Chest"},
    {"chest:F_SP117:2", "Sacred Grove Spinner Chest"},
    {"chest:F_SP117:3", "Lost Woods Lantern Chest"},
    {"chest:F_SP118:15", "Outside Arbiter's Grounds Lantern Chest"},
    {"chest:F_SP118:30", "Bulblin Camp Small Chest in Back of Camp"},
    {"chest:F_SP118:31", "Bulblin Camp First Chest Under Tower At Entrance"},
    {"chest:F_SP121:10", "Lake Hylia Bridge Vines Chest"},
    {"chest:F_SP121:15", "Lake Hylia Bridge Owl Statue Chest"},
    {"chest:F_SP121:2", "Eldin Field Bomb Rock Chest"},
    {"chest:F_SP121:3", "Bridge of Eldin Owl Statue Chest"},
    {"chest:F_SP121:4", "Kakariko Gorge Owl Statue Chest"},
    {"chest:F_SP121:5", "Kakariko Gorge Double Clawshot Chest"},
    {"chest:F_SP121:6", "Faron Field Bridge Chest"},
    {"chest:F_SP121:7", "Lanayru Field Behind Gate Underwater Chest"},
    {"chest:F_SP121:8", "Lanayru Field Spinner Track Chest"},
    {"chest:F_SP121:9", "Lake Hylia Bridge Cliff Chest"},
    {"chest:F_SP122:11", "Hyrule Field Amphitheater Owl Statue Chest"},
    {"chest:F_SP122:12", "Outside South Castle Town Tightrope Chest"},
    {"chest:F_SP122:13", "Outside South Castle Town Double Clawshot Chasm Chest"},
    {"chest:F_SP122:14", "Outside South Castle Town Fountain Chest"},
    {"chest:F_SP124:0", "Gerudo Desert South Chest Behind Wooden Gates"},
    {"chest:F_SP124:1", "Gerudo Desert Owl Statue Chest"},
    {"chest:F_SP124:10", "Gerudo Desert Campfire West Chest"},
    {"chest:F_SP124:11", "Gerudo Desert Peahat Ledge Chest"},
    {"chest:F_SP124:13", "Gerudo Desert North Small Chest Before Bulblin Camp"},
    {"chest:F_SP124:2", "Gerudo Desert Northeast Chest Behind Gates"},
    {"chest:F_SP124:3", "Gerudo Desert Northwest Chest Behind Gates"},
    {"chest:F_SP124:5", "Gerudo Desert Lone Small Chest"},
    {"chest:F_SP124:6", "Gerudo Desert East Canyon Chest"},
    {"chest:F_SP124:7", "Gerudo Desert West Canyon Chest"},
    {"chest:F_SP124:8", "Gerudo Desert Campfire North Chest"},
    {"chest:F_SP124:9", "Gerudo Desert Campfire East Chest"},
    {"chest:R_SP01:1", "Link's Basement Chest"},
    {"chest:R_SP01:2", "Wrestling With Bo"},
    {"chest:R_SP01:4", "Wooden Sword Chest"},
    {"chest:R_SP109:17", "Kakariko Watchtower Chest"},
    {"chest:R_SP109:23", "Kakariko Inn Chest"},
    {"coral_earring", "Gift From Ralis"},
    {"coro_bottle", "Coro Bottle"},
    {"coro_gate_key", "Coro Gate Key"},
    {"coro_lantern", "Coro Lantern"},
    {"dungeon_map:D_MN11", "Snowpeak Ruins Mansion Map"},
    {"dungeon_reward:D_MN01", "Lakebed Temple Dungeon Reward"},
    {"dungeon_reward:D_MN04", "Goron Mines Dungeon Reward"},
    {"dungeon_reward:D_MN05", "Forest Temple Dungeon Reward"},
    {"dungeon_reward:D_MN06", "Temple of Time Dungeon Reward"},
    {"dungeon_reward:D_MN07", "City in the Sky Dungeon Reward"},
    {"dungeon_reward:D_MN10", "Arbiter's Grounds Dungeon Reward"},
    {"dungeon_reward:D_MN11", "Snowpeak Ruins Dungeon Reward"},
    {"fairy_reward:D_SB01", "Cave of Ordeals Great Fairy Reward"},
    {"fishing_bottle", "Fishing Hole Bottle"},
    {"fishing_heart_piece", "Fishing Hole Heart Piece"},
    {"freestanding:D_MN01A:159", "Lakebed Temple Morpheel Heart Container"},
    {"freestanding:D_MN04A:159", "Goron Mines Fyrus Heart Container"},
    {"freestanding:D_MN05:6", "Forest Temple Big Baba Key"},
    {"freestanding:D_MN05A:159", "Forest Temple Diababa Heart Container"},
    {"freestanding:D_MN06A:159", "Temple of Time Armogohma Heart Container"},
    {"freestanding:D_MN07A:159", "City in the Sky Argorok Heart Container"},
    {"freestanding:D_MN08:129", "Palace of Twilight Collect Both Sols"},
    {"freestanding:D_MN08A:128", "Palace of Twilight Zant Heart Container"},
    {"freestanding:D_MN10A:159", "Arbiter's Grounds Stallord Heart Container"},
    {"freestanding:D_MN11A:159", "Snowpeak Ruins Blizzeta Heart Container"},
    {"freestanding:F_SP103:128", "Ordon Bo Cliff Rupee"},
    {"freestanding:F_SP103:129", "Ordon Rusl House Roof Rupee 2"},
    {"freestanding:F_SP103:130", "Ordon Rupee Under Bridge"},
    {"freestanding:F_SP103:132", "Ordon Rusl House Roof Rupee 1"},
    {"freestanding:F_SP103:133", "Ordon Rupee Under Tall Tree 2"},
    {"freestanding:F_SP103:134", "Ordon Bo Window Rupee 2"},
    {"freestanding:F_SP103:135", "Ordon Rupee Under Tall Tree 1"},
    {"freestanding:F_SP103:136", "Ordon Hidden Rusl House Rupee"},
    {"freestanding:F_SP103:137", "Ordon Tree Short Branch Rupee"},
    {"freestanding:F_SP103:138", "Ordon Bo Window Rupee 1"},
    {"freestanding:F_SP103:139", "Ordon Bo Roof Rupee"},
    {"freestanding:F_SP103:145", "Ordon Rupee In River 2"},
    {"freestanding:F_SP103:148", "Ordon Shield House Ledge Grass Rupee"},
    {"freestanding:F_SP103:149", "Ordon Rupee In River 1"},
    {"freestanding:F_SP103:150", "Ordon Rupee In Grass By Bo"},
    {"freestanding:F_SP103:151", "Ordon Tree Long Branch Rupee"},
    {"freestanding:F_SP108:128", "Faron Woods Coro Boulder Rupee 1"},
    {"freestanding:F_SP108:129", "Faron Woods Coro Boulder Rupee 2"},
    {"freestanding:F_SP108:130", "Faron Woods Coro Boulder Rupee 3"},
    {"freestanding:F_SP108:131", "Faron Woods Coro Boulder Rupee 4"},
    {"freestanding:F_SP109:133", "Kakariko Village Ant House Ledge Box Rupee"},
    {"freestanding:F_SP109:135", "Kakariko Village Hot Spring Ledge Box Rupee"},
    {"freestanding:F_SP109:136", "Kakariko Village Spring Shortcut Box Rupee 1"},
    {"freestanding:F_SP109:137", "Kakariko Village Spring Shortcut Box Rupee 2"},
    {"freestanding:F_SP109:138", "Kakariko Village Bell Rupee"},
    {"freestanding:F_SP109:140", "Kakariko Village Bomb Rock Spire Heart Piece"},
    {"freestanding:F_SP109:141", "Eldin Spring Underwater Boulder Rupee"},
    {"freestanding:F_SP110:128", "Death Mountain Volcano Pipe Ledge Rock Rupee"},
    {"freestanding:F_SP110:129", "Death Mountain Volcano Ledge Rupee 1"},
    {"freestanding:F_SP110:130", "Death Mountain Volcano Ledge Rupee 2"},
    {"freestanding:F_SP110:131", "Death Mountain Volcano Ledge Rupee 3"},
    {"freestanding:F_SP111:142", "Kakariko Graveyard Underwater Boulder Rupee"},
    {"freestanding:F_SP111:145", "Kakariko Graveyard Male Ant"},
    {"freestanding:F_SP113:131", "Zora's Domain Top Ledge Rupee"},
    {"freestanding:F_SP113:132", "Zora's Domain Shortcut Ledge Rupee"},
    {"freestanding:F_SP113:133", "Zora's Domain Throne West Underwater Rupee"},
    {"freestanding:F_SP113:134", "Zora's Domain Throne East Underwater Rupee"},
    {"freestanding:F_SP113:135", "Zora's Domain Throne Northwest Underwater Rupee"},
    {"freestanding:F_SP113:136", "Zora's Domain Throne South Underwater Rupee"},
    {"freestanding:F_SP113:137", "Zora's Domain Throne West Gate Underwater Rupee"},
    {"freestanding:F_SP113:138", "Zora's Domain Throne East Gate Underwater Rupee"},
    {"freestanding:F_SP113:139", "Zora's Domain Shortcut Upper Boulder Rupee"},
    {"freestanding:F_SP113:140", "Zora's Domain Shortcut Lower Boulder Rupee"},
    {"freestanding:F_SP113:141", "Zora's Domain North Underwater Boulder Rupee"},
    {"freestanding:F_SP113:142", "Zora's Domain Central Underwater Boulder Rupee"},
    {"freestanding:F_SP113:149", "Zora's Domain Waterfall Ledge Rupee"},
    {"freestanding:F_SP113:150", "Zora's Domain Behind Waterfall Rupee"},
    {"freestanding:F_SP113:151", "Zora's Domain Vine Ledge Rupee"},
    {"freestanding:F_SP113:159", "Zora's Domain Male Dragonfly"},
    {"freestanding:F_SP114:128", "Snowboarding Top Left Rupee"},
    {"freestanding:F_SP114:129", "Snowboarding Top Right Rupee"},
    {"freestanding:F_SP114:130", "Snowboarding Bridge Ledge Upper Rupee"},
    {"freestanding:F_SP114:131", "Snowboarding Bridge Ledge Middle Rupee"},
    {"freestanding:F_SP114:132", "Snowboarding Bridge Ledge Bottom Rupee"},
    {"freestanding:F_SP114:133", "Snowboarding Snowy Tree Top Rupee 1"},
    {"freestanding:F_SP114:134", "Snowboarding Snowy Tree Top Rupee 2"},
    {"freestanding:F_SP114:135", "Snowboarding Snowy Tree Top Rupee 3"},
    {"freestanding:F_SP114:136", "Snowboarding Shortcut Rupee 1"},
    {"freestanding:F_SP114:137", "Snowboarding Shortcut Rupee 2"},
    {"freestanding:F_SP114:138", "Snowboarding Shortcut Rupee 3"},
    {"freestanding:F_SP114:139", "Snowboarding Shortcut Rupee 4"},
    {"freestanding:F_SP114:140", "Snowboarding Shortcut Rupee 5"},
    {"freestanding:F_SP114:141", "Snowboarding Shortcut Rupee 6"},
    {"freestanding:F_SP114:142", "Snowboarding Shortcut Rupee 7"},
    {"freestanding:F_SP114:143", "Snowboarding Shortcut Rupee 8"},
    {"freestanding:F_SP114:144", "Snowboarding Shortcut Rupee 9"},
    {"freestanding:F_SP114:145", "Snowboarding Shortcut Rupee 10"},
    {"freestanding:F_SP114:146", "Snowboarding Shortcut Rupee 11"},
    {"freestanding:F_SP115:128", "Lake Hylia Right Underwater Pillar Rupee"},
    {"freestanding:F_SP115:129", "Lake Hylia Left Underwater Pillar Rupee"},
    {"freestanding:F_SP115:143", "Lanayru Spring Lower Underwater Boulder Rupee"},
    {"freestanding:F_SP115:144", "Lanayru Spring Upper Underwater Boulder Rupee"},
    {"freestanding:F_SP115:154", "Lake Hylia Left Underwater Boulder Rupee"},
    {"freestanding:F_SP115:155", "Lake Hylia Right Underwater Boulder Rupee"},
    {"freestanding:F_SP117:152", "Sacred Grove Female Snail"},
    {"freestanding:F_SP117:153", "Sacred Grove Male Snail"},
    {"freestanding:F_SP118:154", "Bulblin Guard Key"},
    {"freestanding:F_SP118:159", "Bulblin Camp Roasted Boar"},
    {"freestanding:F_SP121:128", "Goron Springwater Rush"},
    {"freestanding:F_SP121:129", "Faron Field Tree Heart Piece"},
    {"freestanding:F_SP121:130", "Kakariko Gorge Spire Heart Piece"},
    {"freestanding:F_SP121:134", "Lanayru Field South Underwater Boulder Rupee"},
    {"freestanding:F_SP121:135", "Lanayru Field North Underwater Boulder Rupee"},
    {"freestanding:F_SP121:136", "Lanayru Field Tree Boulder Rupee"},
    {"freestanding:F_SP121:137", "Lanayru Field North Spinner Track Boulder Rupee"},
    {"freestanding:F_SP121:138", "Lanayru Field South Spinner Track Boulder Rupee"},
    {"freestanding:F_SP121:139", "Lake Hylia Bridge Owl Statue Boulder Rupee"},
    {"freestanding:F_SP121:140", "Lake Hylia Bridge Faron Boulder Rupee"},
    {"freestanding:F_SP121:141", "Kakariko Gorge Owl Statue Boulder Rupee"},
    {"freestanding:F_SP121:142", "Kakariko Gorge Spire Boulder Rupee"},
    {"freestanding:F_SP121:143", "Bridge of Eldin Boulder Rupee"},
    {"freestanding:F_SP121:146", "Lake Hylia Bridge Female Mantis"},
    {"freestanding:F_SP121:147", "Lake Hylia Bridge Male Mantis"},
    {"freestanding:F_SP121:148", "Kakariko Gorge Female Pill Bug"},
    {"freestanding:F_SP121:149", "Kakariko Gorge Male Pill Bug"},
    {"freestanding:F_SP121:150", "Bridge of Eldin Female Phasmid"},
    {"freestanding:F_SP121:151", "Bridge of Eldin Male Phasmid"},
    {"freestanding:F_SP121:152", "Eldin Field Female Grasshopper"},
    {"freestanding:F_SP121:153", "Eldin Field Male Grasshopper"},
    {"freestanding:F_SP121:154", "Lanayru Field Female Stag Beetle"},
    {"freestanding:F_SP121:155", "Lanayru Field Male Stag Beetle"},
    {"freestanding:F_SP121:158", "Faron Field Female Beetle"},
    {"freestanding:F_SP121:159", "Faron Field Male Beetle"},
    {"freestanding:F_SP122:131", "Outside South Castle Town Boulder Rupee"},
    {"freestanding:F_SP122:132", "West Hyrule Field Northern Boulder Rupee"},
    {"freestanding:F_SP122:133", "West Hyrule Field Southern Boulder Rupee"},
    {"freestanding:F_SP122:144", "Outside South Castle Town Female Ladybug"},
    {"freestanding:F_SP122:145", "Outside South Castle Town Male Ladybug"},
    {"freestanding:F_SP122:156", "West Hyrule Field Female Butterfly"},
    {"freestanding:F_SP122:157", "West Hyrule Field Male Butterfly"},
    {"freestanding:F_SP124:152", "Gerudo Desert Female Dayfly"},
    {"freestanding:F_SP124:153", "Gerudo Desert Male Dayfly"},
    {"freestanding:F_SP126:145", "Upper Zora's River Central Underwater Boulder Rupee"},
    {"freestanding:F_SP126:146", "Upper Zora's River West Underwater Boulder Rupee"},
    {"freestanding:F_SP126:147", "Upper Zora's River East Underwater Boulder Rupee"},
    {"freestanding:F_SP126:148", "Upper Zora's River Ledge Boulder Rupee"},
    {"freestanding:F_SP126:158", "Upper Zora's River Female Dragonfly"},
    {"freestanding:F_SP127:128", "Fishing Hole Heart Piece"},
    {"freestanding:F_SP128:139", "Cats Hide and Seek Minigame"},
    {"freestanding:R_SP109:144", "Kakariko Village Female Ant"},
    {"goats_reward", "Herding Goats Reward"},
    {"golden_wolf:15361", "Gerudo Desert Golden Wolf"},
    {"golden_wolf:15362", "Outside South Castle Town Golden Wolf"},
    {"golden_wolf:15364", "West Hyrule Field Golden Wolf"},
    {"golden_wolf:15368", "Ordon Spring Golden Wolf"},
    {"golden_wolf:15376", "Faron Woods Golden Wolf"},
    {"golden_wolf:15680", "North Castle Town Golden Wolf"},
    {"golden_wolf:15744", "Kakariko Graveyard Golden Wolf"},
    {"goron_reward:F_SP113", "Zora's Domain Underwater Goron"},
    {"goron_springwater_rush", "Goron Springwater Rush"},
    {"ilia_charm", "Ilia Charm"},
    {"ilia_memory", "Ilia Memory Reward"},
    {"iza_reward_1", "Iza Helping Hand"},
    {"iza_reward_2", "Iza Raging Rapids Minigame"},
    {"jovani_reward_1", "Jovani 20 Poe Soul Reward"},
    {"jovani_reward_2", "Jovani 60 Poe Soul Reward"},
    {"key_shard_1:D_MN04", "Goron Mines Gor Amato Key Shard"},
    {"key_shard_2:D_MN04", "Goron Mines Gor Ebizo Key Shard"},
    {"key_shard_3:D_MN04", "Goron Mines Gor Liggs Key Shard"},
    {"master_sword", "Sacred Grove Pedestal Master Sword"},
    {"ordon_shield", "Ordon Shield"},
    {"ordon_sword", "Ordon Sword"},
    {"plumm_minigame_reward", "Plumm Fruit Balloon Minigame"},
    {"poe:D_MN06:24", "Temple of Time Poe Above Scales"},
    {"poe:D_MN06:25", "Temple of Time Poe Behind Gate"},
    {"poe:D_MN07:84", "City in the Sky Garden Island Poe"},
    {"poe:D_MN07:85", "City in the Sky Poe Above Central Fan"},
    {"poe:D_MN10:30", "Arbiter's Grounds Torch Room Poe"},
    {"poe:D_MN10:31", "Arbiter's Grounds East Turning Room Poe"},
    {"poe:D_MN10:32", "Arbiter's Grounds Hidden Wall Poe"},
    {"poe:D_MN10:33", "Arbiter's Grounds West Poe"},
    {"poe:D_MN11:114", "Snowpeak Ruins Lobby Poe"},
    {"poe:D_MN11:127", "Snowpeak Ruins Ice Room Poe"},
    {"poe:D_MN11:21", "Snowpeak Ruins Lobby Armor Poe"},
    {"poe:D_SB01:69", "Cave of Ordeals Floor 17 Poe"},
    {"poe:D_SB01:70", "Cave of Ordeals Floor 33 Poe"},
    {"poe:D_SB01:71", "Cave of Ordeals Floor 44 Poe"},
    {"poe:D_SB02:96", "Eldin Lantern Cave Poe"},
    {"poe:D_SB03:93", "Lake Lantern Cave Second Poe"},
    {"poe:D_SB03:94", "Lake Lantern Cave First Poe"},
    {"poe:D_SB03:95", "Lake Lantern Cave Final Poe"},
    {"poe:D_SB05:10", "Lanayru Field Poe Grotto Right Poe"},
    {"poe:D_SB05:11", "Lanayru Field Poe Grotto Left Poe"},
    {"poe:D_SB07:15", "Gerudo Desert Rock Grotto First Poe"},
    {"poe:D_SB07:16", "Gerudo Desert Rock Grotto Second Poe"},
    {"poe:F_SP108:93", "Faron Mist Poe"},
    {"poe:F_SP109:94", "Kakariko Village Bomb Shop Poe"},
    {"poe:F_SP109:95", "Kakariko Village Watchtower Poe"},
    {"poe:F_SP110:89", "Death Mountain Trail Poe"},
    {"poe:F_SP111:87", "Kakariko Graveyard Grave Poe"},
    {"poe:F_SP111:88", "Kakariko Graveyard Open Poe"},
    {"poe:F_SP113:73", "Zora's Domain Waterfall Poe"},
    {"poe:F_SP113:74", "Zora's Domain Mother and Child Isle Poe"},
    {"poe:F_SP114:123", "Snowpeak Poe Among Trees"},
    {"poe:F_SP114:124", "Snowpeak Above Freezard Grotto Poe"},
    {"poe:F_SP114:125", "Snowpeak Blizzard Poe"},
    {"poe:F_SP114:126", "Snowpeak Icy Summit Poe"},
    {"poe:F_SP114:127", "Snowpeak Cave Ice Poe"},
    {"poe:F_SP115:70", "Lake Hylia Alcove Poe"},
    {"poe:F_SP115:71", "Isle of Riches Poe"},
    {"poe:F_SP115:75", "Lake Hylia Dock Poe"},
    {"poe:F_SP115:76", "Lake Hylia Tower Poe"},
    {"poe:F_SP115:77", "Flight By Fowl Ledge Poe"},
    {"poe:F_SP117:15", "Sacred Grove Master Sword Poe"},
    {"poe:F_SP117:16", "Lost Woods Boulder Poe"},
    {"poe:F_SP117:17", "Lost Woods Waterfall Poe"},
    {"poe:F_SP117:30", "Sacred Grove Temple of Time Owl Statue Poe"},
    {"poe:F_SP118:120", "Bulblin Camp Poe"},
    {"poe:F_SP118:90", "Outside Arbiter's Grounds Poe"},
    {"poe:F_SP121:51", "Lanayru Field Bridge Poe"},
    {"poe:F_SP121:57", "Faron Field Poe"},
    {"poe:F_SP121:58", "Kakariko Gorge Poe"},
    {"poe:F_SP121:59", "Lake Hylia Bridge Cliff Poe"},
    {"poe:F_SP122:48", "Outside South Castle Town Poe"},
    {"poe:F_SP122:71", "East Castle Town Bridge Poe"},
    {"poe:F_SP122:73", "Hyrule Field Amphitheater Poe"},
    {"poe:F_SP124:51", "Outside Bulblin Camp Poe"},
    {"poe:F_SP124:91", "Gerudo Desert North Peahat Poe"},
    {"poe:F_SP124:92", "Gerudo Desert East Poe"},
    {"poe:F_SP124:93", "Gerudo Desert Poe Above Cave of Ordeals"},
    {"poe:F_SP126:72", "Upper Zora's River Poe"},
    {"poe:F_SP128:64", "Hidden Village Poe"},
    {"poe:R_SP160:30", "Jovani House Poe"},
    {"prayer_reward", "Charlo Donation Blessing"},
    {"renado_letter", "Renado's Letter"},
    {"sera_reward", "Ordon Cat Rescue"},
    {"shad_dominion_rod", "Shad Dominion Rod"},
    {"shadow_crystal", "Sacred Grove Pedestal Shadow Crystal"},
    {"shop:F_SP116:0:16", "Castle Town Goron Shop Arrow Refill"},
    {"shop:R_SP01:1:75", "Sera Shop Slingshot"},
    {"shop:R_SP109:1:80", "Barnes Bomb Bag"},
    {"shop:R_SP109:3:43", "Kakariko Village Malo Mart Wooden Shield"},
    {"shop:R_SP109:3:44", "Kakariko Village Malo Mart Hylian Shield"},
    {"shop:R_SP109:3:62", "Kakariko Village Malo Mart Hawkeye"},
    {"shop:R_SP109:3:97", "Kakariko Village Malo Mart Red Potion"},
    {"shop:R_SP160:0:48", "Castle Town Malo Mart Magic Armor"},
    {"shop:R_SP160:4:102", "Castle Town Goron Shop Lantern Oil"},
    {"shop:R_SP160:4:44", "Castle Town Goron Shop Hylian Shield"},
    {"shop:R_SP160:4:97", "Castle Town Goron Shop Red Potion"},
    {"sky:F_SP108:8", "Faron Woods Owl Statue Sky Character"},
    {"sky:F_SP121:0", "Bridge of Eldin Owl Statue Sky Character"},
    {"sky:F_SP121:13", "Lake Hylia Bridge Owl Statue Sky Character"},
    {"sky:F_SP121:3", "Kakariko Gorge Owl Statue Sky Character"},
    {"sky:F_SP122:8", "Hyrule Field Amphitheater Owl Statue Sky Character"},
    {"sky:F_SP124:0", "Gerudo Desert Owl Statue Sky Character"},
    {"skybook", "Skybook From Impaz"},
    {"snowboard_race_reward", "Snowboard Racing Prize"},
    {"star_reward_1", "STAR Prize 1"},
    {"star_reward_2", "STAR Prize 2"},
    {"telma_invoice", "Telma Invoice"},
    {"uli_cradle_reward", "Uli Cradle Delivery"},
    {"wood_statue", "Wooden Statue"},
    {"zora_armor", "Rutela's Blessing"},
};

const char* const kItems[256] = {
      nullptr,
      "a Green Rupee",
      "a Blue Rupee",
      "a Yellow Rupee",
      "a Red Rupee",
      "a Purple Rupee",
      "a Orange Rupee",
      "a Silver Rupee",
      nullptr,
      nullptr,
      "Bombs 5",
      "Bombs 10",
      "Bombs 20",
      "Bombs 30",
      "Arrows 10",
      "Arrows 20",
      "Arrows 30",
      nullptr,
      "Seeds 50",
      "a Foolish Item",
      "the Ordon Spring Portal",
      "the South Faron Portal",
      "Water Bombs 5",
      "Water Bombs 10",
      "Water Bombs 15",
      nullptr,
      "Bomblings 5",
      "Bomblings 10",
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      "a Piece of Heart",
      "a Heart Container",
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      "the Ordon Shield",
      "the Wooden Shield",
      "the Hylian Shield",
      nullptr,
      nullptr,
      nullptr,
      "the Magic Armor",
      "the Zora Armor",
      "the Shadow Crystal",
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      "the Upper Zora's River Portal",
      "the Castle Town Portal",
      "the Gerudo Desert Portal",
      "the North Faron Portal",
      nullptr,
      "the Hawkeye",
      nullptr,
      "the Gale Boomerang",
      "the Spinner",
      "the Ball and Chain",
      nullptr,
      nullptr,
      "the Iron Boots",
      nullptr,
      nullptr,
      "the Lantern",
      nullptr,
      nullptr,
      "the Slingshot",
      nullptr,
      "the Kakariko Gorge Portal",
      "the Kakariko Village Portal",
      "the Giant Bomb Bag",
      "the Bomb Bag",
      nullptr,
      "the Death Mountain Portal",
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      "the Zora's Domain Portal",
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      "an Empty Bottle",
      "a Red Potion",
      nullptr,
      "a Blue Potion",
      nullptr,
      "a Bottle with Half Milk",
      "Lantern Oil",
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      "Great Fairy's Tears",
      nullptr,
      "a Bottle with Great Fairy's Tears",
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      "the Renado's Letter",
      "the Invoice",
      "the Wooden Statue",
      "the Ilia's Charm",
      "the Horse Call",
      "a Forest Temple Small Key",
      "a Goron Mines Small Key",
      "a Lakebed Temple Small Key",
      "a Arbiter's Grounds Small Key",
      "a Snowpeak Ruins Small Key",
      "a Temple of Time Small Key",
      "a City in the Sky Small Key",
      "a Palace of Twilight Small Key",
      "a Hyrule Castle Small Key",
      "the Gerudo Desert Bulblin Camp Key",
      "the Lake Hylia Portal",
      "the Auru's Memo",
      "the Ashei's Sketch",
      "the Forest Temple Big Key",
      "the Lakebed Temple Big Key",
      "the Arbiter's Grounds Big Key",
      "the Temple of Time Big Key",
      "the City in the Sky Big Key",
      "the Palace of Twilight Big Key",
      "the Hyrule Castle Big Key",
      "the Forest Temple Compass",
      "the Goron Mines Compass",
      "the Lakebed Temple Compass",
      nullptr,
      "a Bottle with Lantern Oil",
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      "a Mirror Shard",
      "a Mirror Shard",
      "a Mirror Shard",
      "the Arbiter's Grounds Compass",
      "the Snowpeak Ruins Compass",
      "the Temple of Time Compass",
      "the City in the Sky Compass",
      "the Palace of Twilight Compass",
      "the Hyrule Castle Compass",
      "the Mirror Chamber Portal",
      "the Snowpeak Portal",
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      "the Forest Temple Dungeon Map",
      "the Goron Mines Dungeon Map",
      "the Lakebed Temple Dungeon Map",
      "the Arbiter's Grounds Dungeon Map",
      "the Snowpeak Ruins Dungeon Map",
      "the Temple of Time Dungeon Map",
      "the City in the Sky Dungeon Map",
      "the Palace of Twilight Dungeon Map",
      "the Hyrule Castle Dungeon Map",
      "the Sacred Grove Portal",
      "a Male Beetle",
      "a Female Beetle",
      "a Male Butterfly",
      "a Female Butterfly",
      "a Male Stag Beetle",
      "a Female Stag Beetle",
      "a Male Grasshopper",
      "a Female Grasshopper",
      "a Male Phasmid",
      "a Female Phasmid",
      "a Male Pill Bug",
      "a Female Pill Bug",
      "a Male Mantis",
      "a Female Mantis",
      "a Male Ladybug",
      "a Female Ladybug",
      "a Male Snail",
      "a Female Snail",
      "a Male Dragonfly",
      "a Female Dragonfly",
      "a Male Ant",
      "a Female Ant",
      "a Male Dayfly",
      "a Female Dayfly",
      "a Fused Shadow",
      "a Fused Shadow",
      "a Fused Shadow",
      "a Mirror Shard",
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      "a Poe Soul",
      "the Ending Blow",
      "the Shield Attack",
      "the Back Slice",
      "the Helm Splitter",
      "the Mortal Draw",
      "the Jump Strike",
      "the Great Spin",
      "the Bridge of Eldin Portal",
      "the Ancient Sky Book",
      "an Ancient Sky Character",
      "the Ancient Sky Book",
      nullptr,
      "a Purple Rupee",
      "the North Faron Woods Gate Key",
      nullptr,
      nullptr,
      nullptr,
      nullptr,
      "the Gate Keys",
      "the Ordon Pumpkin",
      "the Ordon Cheese",
      "the Snowpeak Ruins Bedroom Key",
      nullptr,
      nullptr,
      "a Goron Mines Key Shard",
      "a Goron Mines Key Shard",
      "a Goron Mines Key Shard",
      nullptr,
      "a Goron Mines Key Shard",
      "the Faron Woods Coro Key",
      nullptr,
};

}

const char* check_place_name(const char* check) {
    if (check == nullptr) return nullptr;
    if (std::strncmp(check, "freestanding:D_MN05B:", 21) == 0) return "Forest Temple Gale Boomerang";
    size_t lo = 0, hi = sizeof(kPlaces) / sizeof(kPlaces[0]);
    while (lo < hi) {
        const size_t mid = (lo + hi) / 2;
        const int cmp = std::strcmp(kPlaces[mid].check, check);
        if (cmp == 0) return kPlaces[mid].place;
        if (cmp < 0) lo = mid + 1; else hi = mid;
    }
    return nullptr;
}

const char* rando_item_name(uint8_t item) {
    return kItems[item];
}
